#  Unemployment Rate Analysis in India

## Project Overview

This project analyzes unemployment rate data in India using Python. The objective is to understand unemployment trends, explore the impact of the COVID-19 pandemic, identify seasonal patterns, and generate insights that can support economic and social policy decisions.

---

## Objectives

- Clean and prepare the dataset for analysis.
- Explore unemployment trends across different regions.
- Analyze the impact of COVID-19 on unemployment rates.
- Identify seasonal or monthly patterns.
- Visualize important findings.
- Present actionable insights based on the analysis.

---

## Dataset

The dataset contains information about unemployment rates in different regions of India up to November 2020.

---

## Tools Used

- Python
- Pandas
- NumPy
- Matplotlib
- Plotly Express
- Jupyter Notebook

In [23]:
import pandas as pd
import numpy as np
import calendar
import plotly.graph_objects as go
import plotly.express as px

import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('../data/raw/Unemployment_Rate_upto_11_2020.csv')
df.head()

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Region.1,longitude,latitude
0,Andhra Pradesh,31-01-2020,M,5.48,16635535,41.02,South,15.9129,79.74
1,Andhra Pradesh,29-02-2020,M,5.83,16545652,40.90,South,15.9129,79.74
2,Andhra Pradesh,31-03-2020,M,5.79,15881197,39.18,South,15.9129,79.74
3,Andhra Pradesh,30-04-2020,M,20.51,11336911,33.10,South,15.9129,79.74
4,Andhra Pradesh,31-05-2020,M,17.43,12988845,36.46,South,15.9129,79.74

### Basic Dataset Information

In [25]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print("\nColumn Names")
print(df.columns.tolist())

print("\nDataset Information")
df.info()

Rows    : 267
Columns : 9

Column Names
['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)', ' Estimated Employed', ' Estimated Labour Participation Rate (%)', 'Region.1', 'longitude', 'latitude']

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Region                                    267 non-null    str
 1    Date                                     267 non-null    str
 2    Frequency                                267 non-null    str
 3    Estimated Unemployment Rate (%)          267 non-null    float64
 4    Estimated Employed                       267 non-null    int64
 5    Estimated Labour Participation Rate (%)  267 non-null    float64
 6   Region.1                                  267 non-null    str
 7   longitude                                 267 non-null    float64
 8   latitude                                  267 non-null    float64
dtypes: float64(4), int64(1), str(4)
memory usage: 26.0 KB

### Updating column names

In [26]:
df.rename(columns={
    "Region": "region",
    " Date": "date",
    " Frequency": "frequency",
    " Estimated Unemployment Rate (%)": "unemployment_rate",
    " Estimated Employed": "estimated_employed",
    " Estimated Labour Participation Rate (%)": "labour_participation_rate",
    "Region.1": "zone",
    "longitude": "longitude",
    "latitude": "latitude"
}, inplace=True)

# Display updated column names
df.columns

Index(['region', 'date', 'frequency', 'unemployment_rate',
       'estimated_employed', 'labour_participation_rate', 'zone', 'longitude',
       'latitude'],
      dtype='str')

- Identify duplicate records.
- Check for missing values.
- Convert the `date` column to the appropriate `datetime` data type.
- Add month and month_nb columns

In [27]:
nb = df.duplicated().sum()
print("Number of duplicate rows in the dataset:", nb)

Number of duplicate rows in the dataset: 0

In [28]:
mv = df.isnull().sum()
print("Number of missing values in each column:")
print(mv)

Number of missing values in each column:
region                       0
date                         0
frequency                    0
unemployment_rate            0
estimated_employed           0
labour_participation_rate    0
zone                         0
longitude                    0
latitude                     0
dtype: int64

In [29]:
df['date'] = pd.to_datetime(df['date'] , dayfirst=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   region                     267 non-null    str
 1   date                       267 non-null    datetime64[us]
 2   frequency                  267 non-null    str
 3   unemployment_rate          267 non-null    float64
 4   estimated_employed         267 non-null    int64
 5   labour_participation_rate  267 non-null    float64
 6   zone                       267 non-null    str
 7   longitude                  267 non-null    float64
 8   latitude                   267 non-null    float64
dtypes: datetime64[us](1), float64(4), int64(1), str(3)
memory usage: 23.2 KB

In [30]:
df['month_nb'] = df['date'].dt.month
df['month'] = df['month_nb'].apply(lambda x : calendar.month_abbr[x])
df.head()

,region,date,frequency,unemployment_rate,estimated_employed,labour_participation_rate,zone,longitude,latitude,month_nb,month
0,Andhra Pradesh,2020-01-31,M,5.48,16635535,41.02,South,15.9129,79.74,1,Jan
1,Andhra Pradesh,2020-02-29,M,5.83,16545652,40.90,South,15.9129,79.74,2,Feb
2,Andhra Pradesh,2020-03-31,M,5.79,15881197,39.18,South,15.9129,79.74,3,Mar
3,Andhra Pradesh,2020-04-30,M,20.51,11336911,33.10,South,15.9129,79.74,4,Apr
4,Andhra Pradesh,2020-05-31,M,17.43,12988845,36.46,South,15.9129,79.74,5,May

- Numeric data grouped by months
- Bar plot of unemployment rate and labour participation rate

In [31]:
data = df.groupby(['month'])[['unemployment_rate' , 'estimated_employed' , 'labour_participation_rate']].mean().reset_index()

In [32]:
data = (
    df.groupby(["month_nb", "month"])[
        ["unemployment_rate", "labour_participation_rate"]
    ]
    .mean()
    .reset_index()
    .sort_values("month_nb")
)

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=data["month"],
        y=data["unemployment_rate"],
        name="Unemployment Rate",
        marker_color="indianred",
        text=data["unemployment_rate"],
        texttemplate="%{text:.1f}",
        textposition="outside"
    )
)

fig.add_trace(
    go.Bar(
        x=data["month"],
        y=data["labour_participation_rate"],
        name="Labour Participation Rate",
        marker_color="lightsalmon",
        text=data["labour_participation_rate"],
        texttemplate="%{text:.1f}",
        textposition="outside"
    )
)

fig.update_layout(
    title="Average Monthly Unemployment and Labour Participation Rates",
    xaxis_title="Month",
    yaxis_title="Average Rate (%)",
    barmode="group",
    template="plotly_white"
)

fig.show()

- Average Estimated Employed Citizens by Month

In [33]:
data = (
    df.groupby(["month_nb", "month"])["estimated_employed"]
      .mean()
      .reset_index()
      .sort_values("month_nb")
)

fig = px.bar(
    data_frame=data,
    x="month",
    y="estimated_employed",
    text_auto=".2s",
    color="month",
    title="Average Estimated Employed Citizens by Month",
    labels={
        "month": "Month",
        "estimated_employed": "Average Estimated Employed Citizens"
    }
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Month",
    yaxis_title="Average Estimated Employed Citizens",
    title_x=0.5
)

fig.update_traces(
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Estimated Employed: %{y:,.0f}<extra></extra>"
)

fig.show()

- Region-wise Unemployment Rate Analysis

In [34]:
fig = px.box(
    df.sort_values("region"),
    x="region",
    y="unemployment_rate",
    color="region",
    points="outliers",
    title="Region-wise Distribution of Unemployment Rate"
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Region",
    yaxis_title="Unemployment Rate (%)",
)

fig.show()

- average unemployment rate bar plot

In [35]:
df_region = df.groupby("region")["unemployment_rate"].mean().reset_index().sort_values('unemployment_rate', ascending=False)
fig = px.bar(
    df_region,
    x="region",
    y="unemployment_rate",
    color="region",
    title="Average Unemployment Rate by Region"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Average Unemployment Rate (%)",
)

fig.show()

- Bar plot Unemployment Rate (monthly)

In [36]:
fig = px.bar(
    df.sort_values("unemployment_rate", ascending=False),
    x="region",
    y="unemployment_rate",
    animation_frame="month",
    title="Average Monthly Unemployment Rate in India"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Average Unemployment Rate (%)",
    title_x=0.5,
    coloraxis_showscale=False
)

fig.show()

In [46]:
fig = px.scatter_geo(
    df,
    'longitude',
    'latitude',
    color='region',
    hover_name='region',
    size = 'unemployment_rate',
    scope = 'asia',
    animation_frame='month',
    title='Impact of lockdown on employment in India'
    )

fig.layout.updatemenus[0].buttons[0].args[1]['frame']['duration'] =1000
fig.update_geos(lataxis_range=[5,40],lonaxis_range=[65,100],oceancolor='lightblue',
               showocean=True)

fig.show()

- zone analysis

In [38]:
df.zone.unique()

<ArrowStringArray>
['South', 'Northeast', 'East', 'West', 'North']
Length: 5, dtype: str

- numeric data grouped by region

In [39]:
data = df.groupby('zone')[['unemployment_rate', 'estimated_employed', 'labour_participation_rate']].mean().reset_index()

- Average Unemployment Rate

In [40]:
fig = px.bar(
    data,
    x='zone',
    y = 'unemployment_rate',
    title='Unemployment Rate by Zone',
    color='zone'
)

fig.update_layout(
    xaxis_title="Zone",
    yaxis_title="Average Unemployment Rate (%)",
    coloraxis_showscale=False
)

fig.show()

In [41]:
fig = px.scatter_matrix(
    df,
    dimensions=['unemployment_rate', 'estimated_employed', 'labour_participation_rate'],
    color='zone',
    title='Scatter Matrix of Unemployment Rate, Estimated Employed, and Labour Participation Rate by Zone'
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5
)

fig.show()

In [42]:
fig = px.bar(
    df,
    x='zone',
    y='unemployment_rate',
    color='region',
    title='Unemployment Rate by Zone and Region',
    animation_frame='month'
)

fig.update_layout(
    xaxis_title="Zone",
    yaxis_title="Average Unemployment Rate (%)",
    coloraxis_showscale=False,
    xaxis={'categoryorder':'total descending'},
    width=800,
    height=600
)
fig.layout.updatemenus[0].buttons[0].args[1]['frame']['duration'] =1000

fig.show()

In [43]:
unemployment = df.groupby(['zone','region'])['unemployment_rate'].mean().reset_index()
unemployment.head()

    zone       region  unemployment_rate
0   East        Bihar             19.471
1   East    Jharkhand             19.539
2   East       Odisha              6.462
3   East  West Bengal             10.192
4  North        Delhi             18.414

In [44]:
fig = px.sunburst(
    unemployment,
    path=['zone', 'region'],
    values='unemployment_rate',
    color='unemployment_rate',
    color_continuous_scale='RdBu',
    title='Sunburst Chart of Unemployment Rate by Zone and Region'
)

fig.show()